# Introducción a Python

_"I don't know about the rest of you..._ 
_I came for the language, but I stayed for the community."_

Brett Cannon, Python Core Dev


#### ¿Qué es Python?

*  Creado por [Guido van Rossum](https://es.wikipedia.org/wiki/Guido_van_Rossum) en 1991.
* Lenguaje de programación libre y gratuito. Características:
    * interpretado
    * de alto nivel
    * de propósito general
    * tipado dinámico
    * gestión automática de memoria
    * múltiples paradigmas de programación (OOP, Funcional...)
    * multitud de paquetes para realizar diferentes tareas.

#### Además...

Con una gran comunidad, abierta, diversa, inclusiva...  
- Python Software Foundation
- Python España 
- Python Madrid
- PyLadies Madrid
- Djangogirls

## Instalación de Python, entornos virtuales y gestores de paquetes

### Diferentes distribuciones:
* [PYTHON.ORG](https://www.python.org/)
* [ANACONDA](https://anaconda.org/) 

### Diferentes versiones:
* 2.X
* 3.X

### Entornos virtuales

- El propósito principal de los entornos virtuales de Python es crear un entorno aislado para los proyectos de Python. 

- Esto significa que cada proyecto puede tener sus propias dependencias, independientemente de qué dependencias tenga cada otro proyecto.

### Entornos virtuales

- **venv** es la herramienta estándar para crear entornos virtuales, y ha sido parte de Python desde Python 3.3. A partir de Python 3.4, se instala de forma predeterminada pip en todos los entornos virtuales creados.
- **virtualenv** es una alternativa de terceros (y predecesora) a venv. Permite que los entornos virtuales se utilicen en versiones de Python anteriores a 3.4, que no proporcionan ningún tipo de software o no pueden instalar pip automáticamente en los entornos creados.


### Módulo venv - Python 3.x
#### Crear el entorno virtual

En linux:
```
$ python3 -m venv c:\path\to\myenv
```

En windows:
```
c:\> c:\Python35\python -m venv c:\path\to\myenv
```

### Módulo venv - Python 3.x
#### Activar el entorno virtual
En linux:
```
$ source venv/bin/activate
```

En Windows:
```
c:\> venv\Scripts\activate.bat
```

### Gestión de paquetes con pip
- Puede instalar, actualizar y eliminar paquetes utilizando un programa llamado pip. 
- Python empezó a incluir pip con Python 3.4. Para versiones anteriores, pip debe ser activada como se describe [aquí](https://packaging.python.org/tutorials/installing-packages/#requirements-for-installing-packages).
- Por defecto, pip instalará los paquetes del Índice de Paquetes de Python, [pypi.org](https://pypi.org)


Usando la instalación de Python por defecto
```
$ python    -m pip install SomePackage
```

Usando la versioń por defecto de Python 2
```
$ python2   -m pip install SomePackage
```

Usando la versión específica de Python 2.7
```
$ python2.7 -m pip install SomePackage  # specifically Python 2.7
```

Usando la versión por defecto de Python 3
```
$ python3   -m pip install SomePackage  # default Python 3
```

Usando la versión específica de Python 3.4
```
$ python3.4 -m pip install SomePackage  # specifically Python 3.4
```

Instalar la última versión de “SomeProject”
```
$ pip install "SomeProject"
```

Instalar una versión específica
```
$ pip install "SomeProject==1.4"
```

Instalar una versión compatible con otra versión específica
```
$ pip install "SomeProject~=1.4.2"  
```

Actualizar SomeProject a la última versión de PyPi
```
$ pip install --upgrade SomeProject
```

Instalar una lista de librerías desde un fichero de requirements
```
$ pip install -r requirements.txt
```

Generar un fichero de requirements a partir del virtual env actual
```
$ pip freeze > requirements.txt
```

## 3. Librerías relevantes
#### Ipython, jupyter, numpy, pandas...

### Proyecto Jupyter


### IPython

- Es un shell interactivo que añade funcionalidades extra al modo interactivo incluido con Python.
- Es multiplataforma, es software libre, tiene una enorme comunidad detrás, un desarrollo constante y bien organizado y es extremadamente potente.

### Jupyter Notebook
#### [jupyter.org/try](https://jupyter.org/try)

### Jupyter Notebook & Slides
[https://github.com/damianavila/RISE](https://github.com/damianavila/RISE)


### Jupyter Lab
#### [jupyter.org/try](https://jupyter.org/try)

### Numpy

In [3]:
! pip install numpy

    100% |████████████████████████████████| 17.3MB 1.1MB/s ta 0:00:01


In [4]:
import numpy as np

### Array creation

In [6]:
my_int_list = [1, 2, 3, 4]

#create numpy array from original python list
my_numpy_arr = np.array(my_int_list)

print(my_numpy_arr)

[1 2 3 4]


In [7]:
# Array of zeros
print(np.zeros(10))

# Array of ones with type int
print(np.ones(10, dtype=int))

# Range of numbers
rangeArray = np.array(range(10), int)
print(rangeArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Random array
print(f"Random array: {np.random.rand(5)}\n")

# Random matrix
print(f"Random matrix:\n {np.random.rand(5,4)}\n")

# Random array of integers in a range (say 0-9)
randomArray = np.floor(np.random.rand(10) * 10)
print(f"Random integer array: {randomArray}\n")

# Futher simplification
print(f"Random matrix:\n{np.random.randint(0, 10, (2,5))}\n")

Random array: [0.04752425 0.32876333 0.65318407 0.77854901 0.10221907]

Random matrix:
 [[0.00568129 0.16614453 0.85775616 0.31671229]
 [0.67856692 0.83185249 0.78997159 0.34482478]
 [0.78479077 0.74936952 0.93707904 0.98693664]
 [0.41207378 0.77045939 0.45152296 0.0546325 ]
 [0.61680563 0.75550677 0.10607306 0.61368765]]

Random integer array: [1. 6. 4. 6. 0. 8. 4. 9. 5. 0.]

Random matrix:
[[8 7 1 4 1]
 [3 8 4 8 2]]



In [11]:
integerArray = np.array([1,2,3,4], int)
integerArray2 = np.array([5,6], int)

# Concatenate two arrays
print(np.concatenate((integerArray, integerArray2)))


[1 2 3 4 5 6]


In [12]:
# Multidimensional array
floatArray = np.array([[1,2,3], [4,5,6]], float)
print(floatArray)


[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
# Convert one dimensional to multidimensional arrays
rangeArray = rangeArray.reshape(5, 2)
print(rangeArray)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
# Convert multidimensional to one dimensional array
rangeArray = rangeArray.flatten()
print(rangeArray)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# Concatenation of multi-dimensional arrays
arr1 = np.array([[1,2], [3,4]], int)
arr2 = np.array([[5,6], [7,8]], int)
print(f'array1: \n{arr1}\n')
print(f'array2: \n{arr2}')

array1: 
[[1 2]
 [3 4]]

array2: 
[[5 6]
 [7 8]]


In [18]:
# Based on dimension 1
print(np.concatenate((arr1, arr2), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
# Based on dimension 2
print(np.concatenate((arr1, arr2), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


#### Universal Functions
These functions are defined as functions that operate element-wise on the array elements whether it is a single or multidimensional array.

In [21]:
#create numpy array from original python list
my_numpy_arr = np.array(my_int_list)

#multiply each element by 2
my_numpy_arr * 2

array([ 4,  8, 12, 16])

In [22]:
# Addition
print(f"Array 1 + Array 2\n {arr1 + arr2}\n")

# Multiplication
print(f"Array 1 * Array 2\n {arr1 * arr2}\n")

# Square root
print(f"Square root of Array 1\n {np.sqrt(arr1)}\n")

# Log
print(f"Log of Array 1\n {np.log(arr1)}\n")

Array 1 + Array 2
 [[ 6  8]
 [10 12]]

Array 1 * Array 2
 [[ 5 12]
 [21 32]]

Square root of Array 1
 [[1.         1.41421356]
 [1.73205081 2.        ]]

Log of Array 1
 [[0.         0.69314718]
 [1.09861229 1.38629436]]



#### Aggregation Functions
These functions are useful when we wish to summarise the information contained in an array.

In [23]:
arr1 = np.arange(1,10).reshape(3,3)
print(f'Array 1: \n{arr1}\n')

print(f"Sum of elements of Array 1: {arr1.sum()}\n")

print(f"Sum by row elements of Array 1: {np.sum(arr1, axis=1)}\n")

print(f"Sum by column elements of Array 1: {np.sum(arr1, axis=0)}\n")

Array 1: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of elements of Array 1: 45

Sum by row elements of Array 1: [ 6 15 24]

Sum by column elements of Array 1: [12 15 18]



In [24]:
print(f'Array 1: \n{arr1}\n')

# Mean of array elements
print(f"Mean of elements of Array 1: {arr1.mean()}\n")

# Minimum of array elements
print(f"Minimum of elements of Array 1: {arr1.min()}\n")
# Minimum of elements of Array 1: 1

# Index of maximum of array elements can be found using arg before the funciton name
print(f"Index of minimum of elements of Array 1: {arr1.argmax()}")

Array 1: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean of elements of Array 1: 5.0

Minimum of elements of Array 1: 1

Index of minimum of elements of Array 1: 8


#### Broadcasting
These are a set of rules of how universal functions operate on numpy arrays.

In [25]:
sampleArray = np.array([[5,2,3], [3,4,5], [1,1,1]], int)
print(f"Sample Array\n {sampleArray}\n")

# Get unqiue values
print(f"Unique values: {np.unique(sampleArray)}\n")
# Unique values: [1 2 3 4 5]

# Get diagonal values
print(f"Diagonal\n {sampleArray.diagonal()}\n")
# Diagonal
#  [5 4 1]

# Sort values in the multidimensional array
print(f"Sorted\n {np.sort(sampleArray)}\n")

Sample Array
 [[5 2 3]
 [3 4 5]
 [1 1 1]]

Unique values: [1 2 3 4 5]

Diagonal
 [5 4 1]

Sorted
 [[2 3 5]
 [3 4 5]
 [1 1 1]]



In [26]:
vector = np.array([1,2,3,4], int)
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]], int)
matrix2 = np.array([[1,1,1], [0,0,0], [1,1,1]], int)

# Dot operator
print(f"Dot of Matrix 1 and Matrix 2\n {np.dot(matrix1, matrix2)}\n")

# Cross operator
print(f"Cross of Matrix 1 and Matrix 2\n {np.cross(matrix1, matrix2)}\n")

# Outer operator
print(f"Outer of Matrix 1 and Matrix 2\n {np.outer(matrix1, matrix2)}\n")

# Inner operator
print(f"Inner of Matrix 1 and Matrix 2\n {np.inner(matrix1, matrix2)}")

Dot of Matrix 1 and Matrix 2
 [[ 4  4  4]
 [10 10 10]
 [16 16 16]]

Cross of Matrix 1 and Matrix 2
 [[-1  2 -1]
 [ 0  0  0]
 [-1  2 -1]]

Outer of Matrix 1 and Matrix 2
 [[1 1 1 0 0 0 1 1 1]
 [2 2 2 0 0 0 2 2 2]
 [3 3 3 0 0 0 3 3 3]
 [4 4 4 0 0 0 4 4 4]
 [5 5 5 0 0 0 5 5 5]
 [6 6 6 0 0 0 6 6 6]
 [7 7 7 0 0 0 7 7 7]
 [8 8 8 0 0 0 8 8 8]
 [9 9 9 0 0 0 9 9 9]]

Inner of Matrix 1 and Matrix 2
 [[ 6  0  6]
 [15  0 15]
 [24  0 24]]


#### Slicing, masking and fancy indexing
The last strategy pools in a few tricks too

In [30]:
arr1 = np.array([1,2,3,4], int)
arr2 = np.array([5,6,7,8], int)
print(f'Array 1: \n{arr1}\n')
print(f'Array 2: \n{arr2}\n\n')

# We can compare complete arrays of equal size element wise
print(f"Array 1 > Array 2\n{arr1 > arr2}\n")

# We can compare elements of an array with a given value
print(f"Array 1 == 2\n {arr1 == 2}\n")

Array 1: 
[1 2 3 4]

Array 2: 
[5 6 7 8]


Array 1 > Array 2
[False False False False]

Array 1 == 2
 [False  True False False]



In [31]:
bigArray = np.array(range(10))
print("Array: {}".format(bigArray))

# Slice array from index 0 to 4
print("Array value from index 0 to 4: {}".format(bigArray[:5]))

# Masking using boolean values and operators
mask = (bigArray > 6) | (bigArray < 3)
print("Array values with mask as true: {}".format(bigArray[mask]))

# Fancy indexing
ind = [2,4,6]
print("Array values with index in list: {}".format(bigArray[ind]))

# Combine all three
print("Array values with index in list: {}".format(bigArray[bigArray > 6][:1]))


Array: [0 1 2 3 4 5 6 7 8 9]
Array value from index 0 to 4: [0 1 2 3 4]
Array values with mask as true: [0 1 2 7 8 9]
Array values with index in list: [2 4 6]
Array values with index in list: [7]


### ¡Tu turno!
[Ejercicios de NumPy](01_Ejercicios_numpy.ipynb)