El objetivo de estos ejercicios es servir de referencia y hacer que apliques los conceptos aprendidos más allá de lo básico. 

Las preguntas son de 4 niveles de dificultades, siendo L1 el más fácil y L4 el más difícil.

#### 0. Import numpy as `np` and print the version number.

In [2]:
import numpy as np
print(np.__version__)

1.16.2


## L1

#### 1. Crea un array de enteros de 1D del `0` al `9`

Output: 
```array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])```

In [4]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### 2. Crea una matriz de 3x3 con todos sus valores a `True`

In [5]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 4. Muestra los números impares de una lista de enteros del `1` al `9`

    Input: `arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

    Output: `array([1, 3, 5, 7, 9])`

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

#### 5.2 Reemplaza todos los valores impares por `-1`

Input: `arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Output: `array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])`

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 5.2 Ahora inténtalo _sin cambiar el array original_

Input: 
```arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])```

Output: 
```
out
    array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
    array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```


In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### 6.1 Convierte un array de 1D a 2D con 2 filas

Input: `np.arange(10)`

Output:
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
       ```

In [28]:
arr = np.arange(10)
arr.reshape(2, -1)  # -1 indica que se desconoce el # col

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 6.2 Convierte un array de 1D a 2D con 2 columnas

Input: `np.arange(10)`

Output:
```
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
       ```

In [82]:
arr = np.arange(10)
arr.reshape(-1, 2)  # -1 indica que se desconoce el # col

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### 7.1 Une estos dos arrays verticalmente

Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Output:
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [80]:
# v1
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [81]:
# v2
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### 7.2 Une estos dos arrays horizontalmente

Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Output:
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [25]:
# v1
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [83]:
# v2
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### 8. Obtén la media, mediana y desviación típica de los elementos del array

Input:
```
arr = np.random.random((5, 3))
```

Output:
```
0.4026456309960461 0.27836938509379616 0.29023285811966365
```
(*) Los números probablemente no coincidan al ser random

In [96]:
np.random.seed(100)

arr = np.random.random((5, 3))

mu = np.mean(arr)
med = np.median(arr)
sd = np.std(arr)

print(mu, med, sd)

0.4026456309960461 0.27836938509379616 0.29023285811966365


#### 9. Imprime un array de números decimales mostrando sólo 3 decimales

Input:
```
rand_arr = np.random.random((5,3))
```

Output:
```
   array([[ 0.443,  0.109,  0.97 ],
          [ 0.388,  0.447,  0.191],
          [ 0.891,  0.474,  0.212],
          [ 0.609,  0.518,  0.403]])
```
(*) Los números probablemente no coincidan al ser random

In [97]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)

rand_arr

array([[0.979, 0.812, 0.172],
       [0.816, 0.274, 0.432],
       [0.94 , 0.818, 0.336],
       [0.175, 0.373, 0.006],
       [0.252, 0.796, 0.015]])

## L2

#### 10. Secuencia predeterminada sin "harcoding"

Input:
```
a = np.array([1,2,3])
```

Output:
```
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [39]:
a = np.array([1,2,3])
print(np.repeat(a, 3))
print(np.tile(a, 3))
print(np.concatenate([np.repeat(a, 3), np.tile(a, 3)], axis=0))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


#### 11. Obtén los elementos comunes de dos arrays


Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Output:
```
array([2, 4])
```

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

#### 12. Elimina de `a` los elementos que estén en `b`


Input:
```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Output:
```
array([1,2,3,4])
```

In [47]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

#### 13. Obtén los índices de los elementos que `a` y `b` tienen en común

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Output:
```
(array([1, 3, 5, 7]),)
```

In [50]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

#### 14. Obtén todos los items entre el 5 y el 10 de `a`

Input: 
```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Output:
```
(array([6, 9, 10]),)
```

In [53]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# v1
idx = np.where((a >= 5) & (a <= 10))
a[idx]

array([ 6,  9, 10])

In [56]:
# v2
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

#### 15. Intercambia las filas 0 y 1 de la matriz

Input:
```
arr = np.arange(9).reshape(3,3)
```

Output:
```
array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])
```

In [65]:
arr = np.arange(9).reshape(3,3)

arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [71]:
# aplicado a las columnas
arr = np.arange(9).reshape(3,3)

arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### 16. Invierte el orden de las columnas de un array 2D

Input:
```
arr = np.arange(9).reshape(3,3)
```

Output:
```
array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])
```

In [69]:
arr = np.arange(9).reshape(3,3)

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [73]:
# aplicado a las filas
arr = np.arange(9).reshape(3,3)

arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### 17.1 Crear un array de 5x3 que contenga números random _enteros_ entre el 5 y el 10

In [76]:
np.random.randint(low=5, high=10, size=(5,3))

array([[9, 6, 7],
       [7, 8, 6],
       [8, 9, 8],
       [6, 7, 9],
       [5, 8, 6]])

#### 17.2 Crear un array de 5x3 que contenga números _decimales_ random entre el 5 y el 10

In [79]:
np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

array([[7.30050327, 5.51673517, 6.36576375],
       [8.14994359, 8.66458891, 6.65138431],
       [6.74338014, 6.63270938, 7.99391921],
       [7.64219774, 8.13163679, 7.60109751],
       [7.61719161, 8.66062267, 7.88197402]])

#### 18. Encuentra el índice de la 5ª repetición del número 1

Input: 
```
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```

Output:
```
8
```


In [102]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

np.where(x == 1)[0][n-1]

8

#### 19. Elimina los valores NaN de un array

Input: 
```
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
```

Output:
```
array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [3]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

## Créditos y más ejercicios [aquí](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)